CREATE TABLE quickcash.clientkey (CLIENT_KEY_ID INT NOT NULL AUTO_INCREMENT, LOGIN TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PASSWORD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PRIMARY KEY (CLIENT_KEY_ID)) ENGINE = InnoDB;

CREATE TABLE quickcash.clientpersonaldata (CLIENT_PD_ID INT NOT NULL AUTO_INCREMENT, FIRST_NAME  TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, LAST_NAME  TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PESEL TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, ID_CARD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, COUNTRY TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  VOIVODESHIP TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CITY TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, STREET TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  BUILDING_NUMBER TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, FLAT_NUMBER TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CLIENT_KEY_ID  INT NOT NULL,  PRIMARY KEY (CLIENT_PD_ID), FOREIGN KEY (CLIENT_KEY_ID) REFERENCES quickcash.clientkey(CLIENT_KEY_ID)) ENGINE = InnoDB;

CREATE TABLE quickcash.clientcontactdetails (CLIENT_CD_ID INT NOT NULL AUTO_INCREMENT, COUNTRY_CD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, VOIVODESHIP_CD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  CITY_CD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, STREET_CD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, BUILDING_NUMBER_CD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  FLAT_NUMBER_CD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CLIENT_KEY_ID  INT NOT NULL, PRIMARY KEY (CLIENT_CD_ID), FOREIGN KEY (CLIENT_KEY_ID) REFERENCES quickcash.clientkey(CLIENT_KEY_ID)) ENGINE = InnoDB;

CREATE TABLE quickcash.clientaccountbalance (CLIENT_AB_ID INT NOT NULL AUTO_INCREMENT, ACCOUNT_BALANCE  DECIMAL NOT NULL, ACCOUNT_NUMBER TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CLIENT_KEY_ID INT NOT NULL,PRIMARY KEY (CLIENT_AB_ID), FOREIGN KEY (CLIENT_KEY_ID) REFERENCES quickcash.clientkey(CLIENT_KEY_ID)) ENGINE = InnoDB;

CREATE TABLE quickcash.employeeskey (EMPLOYEE_KEY_ID INT NOT NULL AUTO_INCREMENT, LOGIN TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PASSWORD TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PRIMARY KEY (EMPLOYEE_KEY_ID)) ENGINE = InnoDB;

CREATE TABLE quickcash.employessdata (EMPLOYEE_DATA_ID INT NOT NULL AUTO_INCREMENT, FIRST_NAME TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, LAST_NAME TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  EMPLOYEE_POSITION TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, EMPLOYEE_KEY_ID INT NOT NULL, PRIMARY KEY (EMPLOYEE_DATA_ID), FOREIGN KEY (EMPLOYEE_KEY_ID) REFERENCES quickcash.employeeskey(EMPLOYEE_KEY_ID)) ENGINE = InnoDB;

